# Generated by Django 5.1 on 2024-08-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
    ]
